# Generated by Django 4.1 on 2024-09-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_customuser_denuncia_like_mantenimiento_mecanico_pago_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='hola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='mecanico',
        ),
        migrations.RemoveField(
            model_name='denuncia',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='like',
            name='mecanico',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.DeleteModel(
            name='Mantenimiento',
        ),
        migrations.RemoveField(
            model_name='mecanico',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
        migrations.DeleteModel(
            name='Denuncia',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Mecanico',
        ),
        migrations.DeleteModel(
            name='Pago',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
