# Generated by Django 4.1 on 2024-09-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_customuser_denuncia_like_mantenimiento_mecanico_pago_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
