# Generated by Django 4.1 on 2024-09-14 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_customeruser_delete_usuariorol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='denuncia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customeruser'),
        ),
        migrations.AlterField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customeruser'),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.customeruser'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.customeruser'),
        ),
    ]
